#!/bin/bash

REV="$1"
shift

if \[ \-z "$REV" \]; then
REV="HEAD"
fi

REV_SELECTOR="${REV}\~..${REV}"
SUBJ=$(git log "$REV_SELECTOR" \--pretty=format:"%s")
BODY=$(git log "$REV_SELECTOR" \--pretty=format:"%b")

cru \--rev "${REV}\~:$REV" \
\-m "$SUBJ" \
\--description "$BODY" \
"$@"
